{
    "openapi": "3.0.0",
    "info": {
        "title": "public-example",
        "version": "",
        "description": ""
    },
    "paths": {
        "/upload/token": {
            "get": {
                "responses": {
                    "200": {
                        "description": "OK",
                        "headers": {},
                        "content": {
                            "application/json": {
                                "examples": {
                                    "response": {
                                        "value": "token panhezeng panhezeng"
                                    }
                                }
                            }
                        }
                    }
                },
                "summary": "Token",
                "description": "",
                "tags": [
                    "Upload"
                ]
            }
        },
        "/upload/{data}": {
            "post": {
                "responses": {
                    "200": {
                        "description": "OK",
                        "headers": {},
                        "content": {
                            "application/json": {
                                "examples": {
                                    "response": {
                                        "value": {
                                            "Key": "panhezeng"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "summary": "",
                "description": "",
                "tags": [
                    "Upload"
                ],
                "parameters": [
                    {
                        "name": "data",
                        "in": "path",
                        "description": "",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ]
            },
            "put": {
                "responses": {
                    "200": {
                        "description": "OK",
                        "headers": {},
                        "content": {
                            "application/json": {
                                "examples": {
                                    "response": {
                                        "value": {
                                            "Key": "panhezeng"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "summary": "",
                "description": "",
                "tags": [
                    "Upload"
                ],
                "parameters": [
                    {
                        "name": "data",
                        "in": "path",
                        "description": "",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ]
            }
        },
        "/el-select-remote-multiple/options": {
            "get": {
                "responses": {
                    "200": {
                        "description": "OK",
                        "headers": {},
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "count": {
                                            "type": "number"
                                        },
                                        "data": {
                                            "type": "array",
                                            "items": {}
                                        }
                                    }
                                },
                                "examples": {
                                    "response": {
                                        "value": {
                                            "count": 100,
                                            "data": [
                                                {
                                                    "id": "1",
                                                    "name": "Option name 1"
                                                }
                                            ]
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "summary": "Options List",
                "description": "",
                "tags": [
                    "ElSelectRemoteMultiple"
                ],
                "parameters": [
                    {
                        "name": "limit",
                        "in": "query",
                        "description": "",
                        "required": false,
                        "example": "20",
                        "schema": {
                            "type": "number"
                        }
                    },
                    {
                        "name": "offset",
                        "in": "query",
                        "description": "",
                        "required": false,
                        "schema": {
                            "type": "number"
                        }
                    },
                    {
                        "name": "search",
                        "in": "query",
                        "description": "",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    }
                ]
            }
        },
        "/el-select-remote-multiple/option": {
            "post": {
                "responses": {
                    "200": {
                        "description": "OK",
                        "headers": {},
                        "content": {
                            "application/json": {
                                "examples": {
                                    "response": {
                                        "value": {
                                            "id": "2",
                                            "name": "Option name 2"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "summary": "Option Create",
                "description": "",
                "tags": [
                    "ElSelectRemoteMultiple"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "name": {
                                        "type": "string"
                                    }
                                },
                                "example": {
                                    "name": "Option name 2"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "tags": [
        {
            "name": "Upload"
        },
        {
            "name": "ElSelectRemoteMultiple"
        }
    ],
    "components": {
        "schemas": {
            "Token": {},
            "File": {},
            "FileModel": {},
            "Options_List": {},
            "Option_Create": {},
            "ElSelectRemoteMultiple_Option": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    }
                }
            },
            "ElSelectRemoteMultiple_Options": {
                "type": "object",
                "properties": {
                    "count": {
                        "type": "number"
                    },
                    "data": {
                        "type": "array",
                        "items": {}
                    }
                }
            }
        }
    }
}